@startuml 演習7-0
|客|
|店員|

|客|
start
:レジに弁当を持っていく;

|店員|
fork
|客|
:代金を支払う;
|客|
|店員|
:清算する;
|店員|
|店員|
fork again
if (温めますか？) then (Yes)
:弁当を温める;
else (no)
endif
:弁当を袋に入れる;
endfork
|店員|

|客|
:弁当を手に持つ;
stop

@enduml