@startuml 演習3-7
class テレビ {
    型式: V12345
}

class 冷蔵庫 {
    型式: R8765
}

class プロジェクタ {
    型式: P1122
}

class 顧客 {
    名前: 高橋洋平, 高田利恵, 大坪直之
}

class 注文 {
    顧客名
    商品
    数量
    注文日
}

顧客 --> 注文
注文 --> テレビ
注文 --> 冷蔵庫
注文 --> プロジェクタ: 注文されていないが、見ていた

@enduml
