@startuml 演習6-4-3

actor 客
participant "料金装置" as 装置
participant ボタン
participant "ベンダー措置" as ベンダー

activate 客
客 -> 装置: 料金投入
activate 装置
装置 --> ボタン: 料金投入済み
activate ボタン
ボタン -> ベンダー: ボタン選択
activate ベンダー
ベンダー --> ボタン: ドリンク排出完了
deactivate ベンダー
deactivate ボタン
装置 --> 客: ドリンク受取
deactivate 装置
deactivate 客

@enduml
