@startuml 演習6-5-1

class ライントレーサー {

光センサー: 光センサー
右モータ: 右モータ
左モータ: 左モータ
CPU: CPU
電源SW: 電源SW
起動()
停止()
}
class 光センサー {

判断する(): string
}
class 右モータ {

ON()
OFF()
}
class 左モータ {

ON()
OFF()
}
class CPU {
}

class 電源SW {

入れる()
切る()
}
ライントレーサー "1" --> "1" 光センサー
ライントレーサー "1" --> "1" 右モータ
ライントレーサー "1" --> "1" 左モータ
ライントレーサー "1" --> "1" CPU
ライントレーサー "1" --> "1" 電源SW

@enduml