@startuml 演習6-4-5

[*] --> 待機 : 状態初期化

state 待機 {
  [*] --> 無効 : ボタン未押下
  無効 --> 有効 : ボタン押下
  有効 --> お金入力 : お金を入れる
}

state お金入力 {
  [*] --> 待機 : お金未入力
  待機 --> ボタン押下 : お金入力済み
}

state ボタン押下 {
  [*] --> 待機 : ドリンク未取得
  待機 --> ドリンク取得 : ドリンク取得可能
}

state ドリンク取得 {
  [*] --> 待機 : ドリンク取得完了
}

@enduml
