@startuml 演習6-4-1

class 自動販売機 {
  - ボタン[10]
  - 料金装置
  - ベンダー装置
}

class ボタン {
  + 押す()
}

class 料金装置 {
  + お金を入れる()
}

class ベンダー装置 {
  + 運ぶ(ドリンク)
  + 集める料金()
}

class ドリンク {
  - 残りの量
  + 残りが半分以下かどうか()
}

自動販売機 --> ボタン
自動販売機 --> 料金装置
自動販売機 --> ベンダー装置
ベンダー装置 --> ドリンク

@enduml
