@startuml 演習3-6
class 人 {
    名前
}

class 高橋洋平 {
    名前: 高橋洋平
}

class 樋口正之 {
    名前: 樋口正之
}

class 試験 {
    名称
}

class 情報処理技術者試験 {
    名称: 情報処理技術者試験
}

class 情報処理安全確保支援士 {
    名称: 情報処理安全確保支援士
}

class LinuC試験 {
    名称: LinuC試験
}

class Level1 {
    名称: Level1
}

class 合格 {
    日付
}

高橋洋平 --> 合格: 情報処理技術者試験の情報処理安全確保支援士
樋口正之 --> 合格: 情報処理技術者試験の情報処理安全確保支援士
高橋洋平 --> 合格: LinuC試験Level１

@enduml